# metamodel_version: 1.7.0
# version: 0.2.0
type MeasurementRecord
  {
    sampleUniqueId: String!
    measurementTime: Datetime!
    instrumentCalibrationDate: Date!
    temperatureCelsius: Float
    temperatureKelvin: Float
    voltageL1: Float
    voltageL2: Float
    voltageL3: Float
    currentL1: Float
    currentL2: Float
    currentL3: Float
  }

type ProjectSubmission
  {
    projectId: String!
    operatorName: String!
    projectStartDate: Date!
    records: [MeasurementRecord]
  }


